# Generated by Django 5.0.13 on 2025-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
